import { NextPage } from "next";
import Head from "next/head";

const SellItem: NextPage = () => {
  return (
  <>
  <Head>
    <title>Sell Item</title>
    <meta name="description" content="Generated by create-t3-app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <main>
     <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
      <h1 className="text-2xl ">
        Here we gonna sell items
      </h1>
    </div>
  </main>
  </>
  );
};

export default SellItem;
